server:
  port: 8085

spring:
  application:
    name: ticho-trace-client-gateway
  cloud:
    gateway:
      routes:
        - id: ticho-trace-client
          uri: http://localhost:8080
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix= 1
        - id: ticho-trace-client2
          uri: http://localhost:8081
          predicates:
            - Path=/client2/**
          filters:
            - StripPrefix= 1
  profiles:
    active: remote

logging:
  config: classpath:logback-spring.xml

management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" #开启所有接口
