server:
  port: 8080

spring:
  application:
    name: ticho-trace-client
  profiles:
    active: local

logging:
  config: classpath:logback-spring.xml

ticho:
  swagger:
    enable: true
  trace:
    enable: true
    url: http://127.0.0.1:8000/trace/collect
    logUrl: http://127.0.0.1:8000/log/collect
    order: -1000
    pushLog: true
    pushTrace: true
    secret: 1651402954198106112
    ant-patterns: ["/health"]
  log:
    print: true
    order: -100