server:
  port: 8000

spring:
  application:
    name: trace-server
  profiles:
    active: @spring.active@

easy-es:
  #默认为true,若为false则认为不启用本框架
  enable: true
  # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  address : @es.host@
  username: @es.username@
  password: @es.password@
  banner: false
  connect-timeout: 5000
  socket-timeout: 60000
  global-config:
    print-dsl: false

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES

logging:
  config: classpath:logback-spring.xml

ticho:
  trace:
    trace: '[${traceId}]'
  log:
    print: true
    ant-patterns: ["/swagger-resources/**", "/health", "/*/collect"]
  swagger:
    enable: true
  security:
    ant-patterns: [ "/doc.html", "/swagger-resources/**", "/webjars/**", "/v2/api-docs","/favicon.ico", "/health", "/oauth/token", "/oauth/refreshToken", "/oauth/publicKey"]
  cors:
    enable: true
